apiVersion: v1
kind: Service
metadata:
  name: hcm-backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: hcm-backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
