apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcm-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: hcm-backend
  template:
    metadata:
      labels:
        app: hcm-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          command: ["sh", "-c", "npx prisma migrate deploy && npm start"]
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: DATABASE_URL
              value: {{ .Values.backend.env.DATABASE_URL }}
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
