apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcm-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: hcm-frontend
  template:
    metadata:
      labels:
        app: hcm-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
