apiVersion: v1
kind: Service
metadata:
  name: hcm-frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: hcm-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
