{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hcm-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: hcm-backend
                port:
                  number: {{ .Values.backend.port }}

          - path: /assets
            pathType: Prefix
            backend:
              service:
                name: hcm-frontend
                port:
                  number: {{ .Values.frontend.port }}

          - path: /
            pathType: Prefix
            backend:
              service:
                name: hcm-frontend
                port:
                  number: {{ .Values.frontend.port }}
{{- end }}
