apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcm-backend
  namespace: hcm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hcm-backend
  template:
    metadata:
      labels:
        app: hcm-backend
    spec:
      containers:
        - name: backend
          image: hcm-backend:1.0   # zamie≈Ñ na registry np. ghcr.io/user/hcm-backend:1.0
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres.hcm.svc.cluster.local:5432/hcm"
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: hcm-config
                  key: APP_ENV
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: hcm-config
                  key: APP_VERSION
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 5
