apiVersion: v1
kind: ConfigMap
metadata:
  name: hcm-config
  namespace: hcm
data:
  APP_ENV: "kubernetes"
  APP_VERSION: "1.0.0"
  DATABASE_HOST: "postgres.hcm.svc.cluster.local"
  DATABASE_USER: "postgres"
  DATABASE_DB: "hcm"
