apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hcm-ingress
  namespace: hcm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: hcm.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hcm-frontend
                port:
                  number: 80
