apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hcm-ingress
  namespace: hcm
spec:
  ingressClassName: nginx
  rules:
    - host: tailon.suramar.int
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: hcm-backend
                port:
                  number: 3000

          - path: /assets
            pathType: Prefix
            backend:
              service:
                name: hcm-frontend
                port:
                  number: 80

          - path: /
            pathType: Prefix
            backend:
              service:
                name: hcm-frontend
                port:
                  number: 80
